[tool.poetry]
name = "CVE-2022-28346"
version = "0.1.0"
description = ""
authors = ["ahsentekdemir"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
